### PR TITLE
Add Crystal 1.2 support

### PR DESCRIPTION
**Pull request by refi64**
Based on #27, docker image builds locally but I guess we'll see about CI...

### CODE REVIEW

**Comment by refi64** [comment]
Oops, looks like I forgot to make the needed changes to the macOS CI. Don't have a Mac to test it in particular, but the changes *look* like they should work...

**Comment by refi64** [comment]
...and attempted to fix again, sorry about needing workflow approval every time :sweat_smile:

**Comment by elbywan** [comment]
> ...and attempted to fix again, sorry about needing workflow approval every time 😅

@refi64 No worries this is only clicking a button, thank *you* for contributing! ❤️

**Comment by refi64** [comment]
Looks like it's passing now!

**Comment by elbywan** [comment]
This is great, thanks! ❤️ 

I think I can also remove the need to clone the crystal repo because of the `markd` dependency, I'll make a follow-up PR.

**Pull request merged**
